In [2]:
import os
import pandas as pd
import numpy as np
import above_library.inventory as inv
import importlib

In [3]:
inventory_dir = '/glade/work/afoster/ABoVE/obs_data/inventory_data'
inventory_files = ['NWT_Biophysical_Inventory_2015_2019_LBC.csv',
                   'NWT2022_Tree_Inventory_checkedLBC_Chevy_final_FINAL.csv',
                   'NWT2024_Tree_InventoryLBC_correctedspecies_nobalsamfir.csv'
                  ]
species_df_file = os.path.join(inventory_dir, 'NWT_species_to_PFT.csv')
site_info_file = os.path.join(inventory_dir, 'carbonstocksNWT_fulldatathrough2024_QAQCtoshare-simple.csv')

tree_eqns = pd.read_csv(os.path.join(inventory_dir, 'tree_equations.csv'))
tree_eqns['form'] = 'tree'
shrub_eqns = pd.read_csv(os.path.join(inventory_dir, 'shrub_equations.csv'))
shrub_eqns['form'] = 'shrub'
biomass_eqns = pd.concat([tree_eqns, shrub_eqns]).reset_index()

In [4]:
species_df = pd.read_csv(species_df_file)
site_info = inv.clean_site_dat(site_info_file)

In [55]:
site_av_dfs = []
size_count_dfs = []
height_av_dfs = []
for file in inventory_files:
    file_path = os.path.join(inventory_dir, file)
    site_avs, size_counts, height_avs = inv.get_inventory_data(file_path, species_df, site_info, biomass_eqns)
    site_av_dfs.append(site_avs)
    size_count_dfs.append(size_counts)
    height_av_dfs.append(height_avs)

site_avs = pd.concat(site_av_dfs)
size_counts = pd.concat(size_count_dfs)
height_avs = pd.concat(height_av_dfs)

site_avs["first_year"] = site_avs.groupby(["site"])["year"].transform("min")
site_avs = site_avs[site_avs.first_year == site_avs['year']]

height_avs["first_year"] = height_avs.groupby(["site"])["year"].transform("min")
height_avs = height_avs[height_avs.first_year == height_avs['year']]

In [56]:
site_avs.to_csv(os.path.join('/glade/work/afoster/ABoVE/obs_data/', 'site_averages.csv'))
size_counts.to_csv(os.path.join('/glade/work/afoster/ABoVE/obs_data/', 'site_structure.csv'))
height_avs.to_csv(os.path.join('/glade/work/afoster/ABoVE/obs_data/', 'height_averages.csv'))

In [57]:
site_info = site_avs[['site', 'latitude', 'longitude', 'type', 'ecoregion']].drop_duplicates()

In [58]:
site_info.to_csv('/glade/work/afoster/ABoVE/obs_data/site_info.csv')

In [8]:
site_avs = pd.read_csv(os.path.join('/glade/work/afoster/ABoVE/obs_data/', 'site_averages.csv'), index_col=[0])
size_counts = pd.read_csv(os.path.join('/glade/work/afoster/ABoVE/obs_data/', 'site_structure.csv'), index_col=[0])

In [29]:
site_avs[(site_avs.pft == 'jack_pine') & (site_avs.prop_basal > 0.4)]

,site,pft,year,count,BA,biomass,totalArea,dens_ha,basal_ha,biomass_tCha,basal_ha_total,prop_basal,latitude,longitude,type,ecoregion,first_year
57,SS82-2,jack_pine,2015,27,235.407193,69.947447,150.0,1800.0,1.569381,2.098423,3.245075,0.483619,61.15220,-119.095625,lowland,NaN,2015
27,ZF46-VAL3,jack_pine,2022,2,228.747022,95.585766,200.0,100.0,1.143735,2.150680,1.640071,0.697369,62.25877,-116.370930,lowland,plain,2022

In [43]:
site_info[site_info.site == 'ZF14-207']

         site  latitude  longitude     type ecoregion
387  ZF14-207  62.43462 -113.15398  lowland    sheild

In [46]:
site_avs[site_avs.site == 'ZF46-VAL301']

,site,pft,year,count,BA,biomass,totalArea,dens_ha,basal_ha,biomass_tCha,basal_ha_total,prop_basal,latitude,longitude,type,ecoregion,first_year
20,ZF46-VAL301,black_spruce,2024,61,864.110454,141.942415,150.0,4066.666667,5.760736,4.258272,19.786556,0.291144,62.211832,-116.323639,upland,plain,2024
21,ZF46-VAL301,broadleaf_colddecid_extratrop_shrub,2024,19,5.254309,0.336869,150.0,1266.666667,0.035029,0.010106,19.786556,0.001770,62.211832,-116.323639,upland,plain,2024
22,ZF46-VAL301,larch,2024,37,1653.348131,546.890894,150.0,2466.666667,11.022321,16.406727,19.786556,0.557061,62.211832,-116.323639,upland,plain,2024
23,ZF46-VAL301,white_spruce,2024,34,445.270530,111.047970,150.0,2266.666667,2.968470,3.331439,19.786556,0.150025,62.211832,-116.323639,upland,plain,2024